cache: bundler

language:
  - ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.7
  - 2.2.3

install:
  - "travis_retry bin/setup"

script:
  - "bundle exec appraisal rake"

branches:
  only:
    - master

sudo: false
