language:
  - ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0

before_install:
  - "sudo apt-get install ca-certificates"
  - "gem update --system"

install:
  - "bundle install"

before_script:
  - "bundle exec rake db:migrate"

branches:
  only:
    - master
