language: ruby
rvm:
  - 1.9.2
  - 1.9.3
before_install:
  - gem update --system
before_script:
  - "bundle exec rake db:migrate"
gemfile:
  - gemfiles/3.0.12.gemfile
  - gemfiles/3.1.4.gemfile
  - gemfiles/3.2.3.gemfile
branches:
  only:
    - master
